### ISSUE TITLE
The weight doesn't change. It's always 1.

### ISSUE THREAD

**Issue by zeehuilin** [Mikoto10032/AutomaticWeightedLoss#3]
Hi, my network has 5 tasks, 2 kinds of loss-- nn.mseloss（point_loss） and Dice (seg_loss)
when I use AutomaticWeightedLoss, the self.params[i] always 1。
![image](https://user-images.githubusercontent.com/30404211/93303138-9f6a9300-f82d-11ea-8d2c-771ad3fb5e18.png)

**Comment by Mikoto10032** [comment]
After communicating with you privately, the problem has been resolved. Hahaha, the params of AutomaticWeightedLoss should also be put in the optimizer. Good luck!:stuck_out_tongue_winking_eye:

**Comment by deryaguler95** [comment]
Can you help us for me I couldnt not resolved that this problem
